const PokemonTypeColor = {
  bg: {
    bug: "bg-[#A8B820]",
    dark: "bg-[#705848]",
    dragon: "bg-[#7038F8]",
    electric: "bg-[#F8D030]",
    fairy: "bg-[#EE99AC]",
    fighting: "bg-[#C03028]",
    fire: "bg-[#F08030]",
    flying: "bg-[#A890F0]",
    ghost: "bg-[#705898]",
    grass: "bg-[#78C850]",
    ground: "bg-[#E0C068]",
    ice: "bg-[#98D8D8]",
    normal: "bg-[#A8A878]",
    poison: "bg-[#A040A0]",
    psychic: "bg-[#F85888]",
    rock: "bg-[#B8A038]",
    steel: "bg-[#B8B8D0]",
    water: "bg-[#6890F0]",
    all: "bg-[#BBBBBB]",
  },
  text: {
    bug: "text-white",
    dark: "text-white",
    dragon: "text-white",
    electric: "text-white",
    fairy: "text-white",
    fighting: "text-white",
    fire: "text-white",
    flying: "text-white",
    ghost: "text-white",
    grass: "text-white",
    ground: "text-white",
    ice: "text-white",
    normal: "text-white",
    poison: "text-white",
    psychic: "text-white",
    rock: "text-white",
    steel: "text-white",
    water: "text-white",
    all: "text-red-500",
  },
};

export default PokemonTypeColor;
